### ISSUE TITLE
[init/#1] Stylelint 초기세팅 

### ISSUE THREAD

**Issue by Ivoryeee** [NOW-SOPT-CDSP-TEAM-WEB2/Client#1]
## 🛠 Issue

- [x] stylelint 초기세팅 

## 📝 To-do

- [x] stylelint 관련 패키지 설치 
- [x] 플젝에 적용할 stylelint 규칙 찾아보고 .stylelintrc에 적용
- [x] stylelint 잘 작동되는지 확인하기!
