### ISSUE TITLE
[Feat] 홈페이지 view

### ISSUE THREAD

**Issue by rtttr1** [NOW-SOPT-CDSP-TEAM-WEB2/Client#11]
## 🛠 Issue

- 홈 헤더 view 구현
- 홈 헤더 애니메이션 적용
- 홈 메인 Layout view 구현
- 홈 푸터 view 구현
## 📝 To-do

- [x] 헤더 view 구현
- [x] 헤더 애니메이션 적용
- [x] 메인 Layout view 구현
- [x] 푸터 view 구현
